### ISSUE TITLE
feature: can result uploader support alibaba cloud oss？

### ISSUE THREAD

**Issue by zjmletang** [HCK-CI/AutoHCK#471]
The autohck project is truly amazing and has greatly improved our testing efficiency. I've noticed that currently, autohck only supports Dropbox, and there are plans to expand support for more result uploaders. I have added support for Alibaba Cloud OSS based on the community's work, and we are using this feature internally. I would like to ask if there is an opportunity to merge this functionality into the upstream community. If so, I will submit a patch for your review.

refer to the official documentation for Alibaba Cloud OSS, as follows.
https://www.alibabacloud.com/en/product/object-storage-service?_p_lc=1

The implementation effect is as follows.
![image](https://github.com/user-attachments/assets/1394ff14-4bc5-4be4-8173-4c7c1d4366c1)

**Comment by kostyanf14** [comment]
@zjmletang feel free to submit pr with any uploaders

**Comment by kostyanf14** [comment]
@zjmletang We have Dropbox support only because we don't need any other except PeopleRedHat which is a private one. Regardless of this AutoHCK is an opensource project and we encourage any new features and/or bug fixes from the community.

**Comment by zjmletang** [comment]
@kostyanf14  Understood,thanks for the clarification. I'am planning to submit a patch soon.

**Comment by kostyanf14** [comment]
done https://github.com/HCK-CI/AutoHCK/pull/476
